# 合成视频配置
video:
  # 字幕字体大小
  fontsize: 12
  # 字体颜色
  fontcolor: FFFFFF
  # 字体文件 要求在项目目录下
  fontFile: simhei.ttf
  # 描边颜色 内描边
  strokeColor: yellow
  # 描边宽
  strokeWidth: 1.2
  # 文字间距
  kerning: 1
  # 字幕位置 越小越靠山 越大越靠下 0 - 1 开启ffmpeg后 6=上 10中 2下
  position: 2
  # 是否开启动画，只有once开启时候才会有动画
  animation: true
  # 动画幅度比例 最佳1.2
  animationSpeed: 1.2
  # 是否开启字幕
  subtitles: true

#sqlite配置
sqlite:
  path: "./"
  port: "8999"
  config: ""
  db-name: "stable-diffusion"
  username: "hyouka"
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

#日志配置
zap:
  level: info
  format: console
  prefix: "[github.com/stable-diffusion-go/server]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
  retention-day: -1

#基础配置
system:
  oss-type: local 

local:
  path: uploads/file
  store-path: uploads/file
