# 书配置 记得要加一个空格！！！！！！！！
book:
  # 小说书名 要和文件同目录 不要带.txt
  name: 原来我是修仙大佬
  # 小说使用的语言 默认 zh | en 为英语 具体请查看阿里云翻译的文档
  language: zh

translate_config:
  type: ollama
# 批量文件处理 使用mass_production.py 文件
batch:
  # 资源文件目录
  source_path:
  # 输出文件目录
  output_path:
  # 尾部视频拼接路径
  ending_splice_path:
# 音频
audio:
  # 每行的字数限制
  limit: 18
  # 角色 终端输入 edge-tts --list-voices 可以查看所有声音
  # 推荐 zh-CN-YunxiNeural 男  zh-CN-XiaoyiNeural  一般  女  zh-CN-XiaoxiaoNeural 最好  女
  voice: zh-CN-YunxiNeural
  # 语速
  rate: +30%
  # 音量
  volume: +100%
  # 是否开启bgm 开启bgm 项目下要有一个bgm的目录
  bgm: true
  # 分贝
  pitch: +0Hz
  # 背景音频分贝db
  bgm_db: -15

# 分词
potential:
  # 角色名字最小长度
  min_length: 2
  # 角色名字最大长度
  max_length: 4
  # 角色数量
  top_n: 2
  # 每张图片的最小文字数量
  min_words: 30
  #  每张图片的最大文字数量
  max_words: 40
  # 是否进行切割
  split: false
# 这里只放常规参数，更多参数请修改stable diffusion.json
stable_diffusion:
  # 服务器ip
  url: http://127.0.0.1:7860
  # 图片高
  height: 960
  # 图片宽
  width: 540
  # lora <lora:lora name:weight> 多个用英文,隔开
  lora: <lora:Fantasy x Guofeng Xianxia Realm_v1.0(国风仙侠-shakker):1>

# 合成视频配置
video:
  # ImageMagick 路径 # C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\magick.exe
  imagemagick_path:
  # 字幕字体大小
  fontsize: 12
  # 字体颜色
  fontcolor: FFFFFF
  # 字体文件 要求在项目目录下
  fontfile: simhei.ttf
  # 描边颜色 内描边
  stroke_color: yellow
  # 描边宽
  stroke_width: 1.2
  # 文字间距
  kerning: 1
  # 字幕位置 越小越靠山 越大越靠下 0 - 1 开启ffmpeg后 6=上 10中 2下
  position: 2
  # 使用moviepy或者ffmpeg合成视频
  use_moviepy: false
  # 一次性合成 不用分段合成 视频效果更好 需要安装ffmpeg环境
  once: true
  # 是否开启动画，只有once开启时候才会有动画
  animation: true
  # 动画幅度比例 最佳1.2
  animation_speed: 1.2
  # 是否开启字幕
  subtitles: true

chatgpt:
  # ForwardKey
  ForwardKey: ollama
  # url
  url: http://localhost:11434/v1
  # 最大token数量
  max_token: 16385
  # 模型
  model: gemma2

ollama:
  # prompt模型
  model: impactframes/llama3_ifai_sd_prompt_mkr_q4km
  # ollama路径
  url: http://localhost:11434/v1


aliyun:
  access_key_id:
  access_key_secret:
